services:
  - type: web
    name: fantasy-viz
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: YAHOO_CLIENT_ID
        sync: false
      - key: YAHOO_CLIENT_SECRET
        sync: false
      - key: YAHOO_REDIRECT_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 5000
